spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/units-service-db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate-ddl-auto: create
    show-sql: true

server:
  port: 8081